spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

  datasource:
    url: jdbc:mysql://192.168.50.10:3307/vision_bigdata_v1
    username: ivm
    password: ivm@ffcs123#

  jackson:
    serialization:
      #保证@ResponseBody时，Date会自动转化为timeStamp的数值(毫秒数)
      WRITE_DATES_AS_TIMESTAMPS : true
    time-zone: GMT+8


  thymeleaf:
    cache: false
    encoding: utf-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html



mybatis:
  mapper-locations: classpath:com/ffcs/face/*/dao/**/*Dao.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
    #org.apache.ibatis.logging.stdout.StdOutImpl


baseUri: http://localhost:10004/bvs/api/v1/
frsBaseUri: http://localhost:5001/frs/api/v1/

